version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    image: fastapi-basic  # Definimos el nombre de la imagen
    ports:
      - "8001:8000"  # Mapeamos el puerto 8001 del contenedor al puerto 8000 de tu máquina
    volumes:
      - ./src:/app  # Sincroniza el código fuente entre el contenedor y tu máquina
    environment:
      - PYTHONUNBUFFERED=1  # Evita que los logs de Python se buffericen
    restart: always  # Reinicia el contenedor si falla